@startuml

class practica.Practica {
    - arr: int[]
    - delay: int
    + Practica()
    - generateUniqueRandomArray(size: int[]): int[]
    - selectionSort(arr: int[]): void
    - binarySearch(arr: int[], target: int): void
    - updateValue(index: int, newValue: int): void
    - valueExists(value: int): boolean
    - deleteValue(value: int): void
    - sleep(delay: int): void
}

class practica.Main {
    + main(String[]) : void
}
Practica --> java.lang.ArrayList : uses
Practica --> java.util.Random : uses
Practica --> java.Integer.Integer : uses
Practica --> java.lang.Thread : uses
Main --> Practica : uses
@enduml
